name: Upload Python Package to PyPI when a Release is Created

on:
  # release:
  #   types: [created]
  push:
    branches: [ "main" ]

jobs:
  # pypi-publish:
  #   name: Publish release to PyPI
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/pyscanline
  #   permissions:
  #     id-token: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.x"
  #     - name: Install dependencies
  #       run: |
  #         . scripts/setup.sh
  #     - name: Build package
  #       run: |
  #         uv build
  #     - name: Publish package distributions to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #     - name: Publish package distributions to TestPyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         repository-url: https://test.pypi.org/legacy/

  testpypi-publish:
    name: Upload release to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyscanline
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          . scripts/setup.sh
      - name: Build package
        run: |
          uv build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          repository-url: https://test.pypi.org/legacy/